// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoQbsjbaiWFrtPh1Ik6CdAYWANQQhcNoA',
    appId: '1:1080576785962:web:c98b98d99b893e49f64d53',
    messagingSenderId: '1080576785962',
    projectId: 'eventsmart-6e0b9',
    authDomain: 'eventsmart-6e0b9.firebaseapp.com',
    storageBucket: 'eventsmart-6e0b9.firebasestorage.app',
    measurementId: 'G-0EWMGRMH0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSj486KAyEs-83dqpnH9tZDjLHQGlFLio',
    appId: '1:1080576785962:android:06cc1826cab47969f64d53',
    messagingSenderId: '1080576785962',
    projectId: 'eventsmart-6e0b9',
    storageBucket: 'eventsmart-6e0b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfv7C2s5wQNO8GV0nsWLj2H1kxtpdPr2U',
    appId: '1:1080576785962:ios:2fa85f260f8b40d5f64d53',
    messagingSenderId: '1080576785962',
    projectId: 'eventsmart-6e0b9',
    storageBucket: 'eventsmart-6e0b9.firebasestorage.app',
    iosBundleId: 'com.example.smartevent',
  );
}
